# This is a config for E2B sandbox template.
# You can use template ID (56m9p3jpzg38a3994gu5) or template name (rice-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("rice-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("rice-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('rice-nextjs-test-2')

team_id = "7fc9b41c-2dcc-4a6e-a1ef-2621fc1ac12b"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "rice-nextjs-test-2"
template_id = "56m9p3jpzg38a3994gu5"
